from PyQt5 import QtCore, QtGui, QtWidgets
from info import w1

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 280)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tempname = QtWidgets.QLabel(self.centralwidget)
        self.Tempname.setGeometry(QtCore.QRect(50, 40, 50, 15))
        self.Tempname.setObjectName("Tempname")
        self.Tempvalue = QtWidgets.QLabel(self.centralwidget)
        self.Tempvalue.setGeometry(QtCore.QRect(150, 40, 50, 15))
        self.Tempvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.Tempvalue.setObjectName("Tempvalue")
        self.Ftempname = QtWidgets.QLabel(self.centralwidget)
        self.Ftempname.setGeometry(QtCore.QRect(50, 70, 50, 15))
        self.Ftempname.setObjectName("Ftempname")
        self.Ftempvalue = QtWidgets.QLabel(self.centralwidget)
        self.Ftempvalue.setGeometry(QtCore.QRect(150, 70, 50, 15))
        self.Ftempvalue.setAlignment(QtCore.Qt.AlignCenter)
        self.Ftempvalue.setObjectName("Ftemavalue")
        self.Weathername = QtWidgets.QLabel(self.centralwidget)
        self.Weathername.setGeometry(QtCore.QRect(50, 100, 50, 15))
        self.Weathername.setObjectName("Weathername")
        self.Weathervalue = QtWidgets.QLabel(self.centralwidget)
        self.Weathervalue.setGeometry(QtCore.QRect(120, 95, 75, 30))
        self.Weathervalue.setLocale(QtCore.QLocale(QtCore.QLocale.Ukrainian, QtCore.QLocale.Ukraine))
        self.Weathervalue.setAlignment(QtCore.Qt.AlignCenter)
        self.Weathervalue.setObjectName("Weathervalue")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(45, 35, 150, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(44, 65, 150, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(44, 95, 150, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(44, 125, 150, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(45, 35, 3, 90))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(120, 35, 3, 90))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(185, 35, 20, 90))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 270, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.butn = QtWidgets.QPushButton(MainWindow)
        self.butn.setObjectName('button')
        self.butn.setText("Закрити програму")
        self.butn.setGeometry(QtCore.QRect(50, 150, 150, 40))
        self.butn.clicked.connect(self.close)
    def close(self, MainWindow):
        MainWindow.close
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Tempname.setText(_translate("MainWindow", "Tempeture"))
        self.Tempvalue.setText(_translate("MainWindow", str(w1.temp)))
        self.Ftempname.setText(_translate("MainWindow", "Feels like"))
        self.Ftempvalue.setText(_translate("MainWindow", str(w1.ftemp)))
        self.Weathername.setText(_translate("MainWindow", "Weather"))
        self.Weathervalue.setText(_translate("MainWindow", w1.weather))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    app.exec()